name: Deploy to Hosting

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Deploy via SSH and Git Pull
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOSTING_HOST }}
        username: ${{ secrets.HOSTING_USERNAME }}
        password: ${{ secrets.HOSTING_PASSWORD }}
        port: ${{ secrets.HOSTING_PORT || 64000 }}
        script: |
          cd /php-planetscale
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git pull origin main
          